
(define 2**16 (expt 2 16))
(define 2**32 (expt 2 32))

(define (+mod16 x y)
  (modulo (+ x y) 2**16))
(define (-mod16 x y)
  (modulo (+ x y) 2**16))
(define (*mod16 x y)
  (modulo (* x y) 2**16))
(define (1+mod16 x)
  (+mod16 x 1))
(define (1-mod16 x)
  (-mod16 x 1))

(define (+mod32 x y)
  (modulo (+ x y) 2**32))
(define (-mod32 x y)
  (modulo (- x y) 2**32))
(define (*mod32 x y)
  (modulo (* x y) 2**32))
(define (1+mod32 x)
  (+mod32 x 1))
(define (1-mod32 x)
  (-mod32 x 1))

(define (data-chunk? x)
  (and (chunk? x) (= (get-chunk-type x) #x00)))
(define (init-chunk? x)
  (and (chunk? x) (= (get-chunk-type x) #x01)))
(define (init-ack-chunk? x)
  (and (chunk? x) (= (get-chunk-type x) #x02)))
(define (sack-chunk? x)
  (and (chunk? x) (= (get-chunk-type x) #x03)))
(define (heartbeat-chunk? x)
  (and (chunk? x) (= (get-chunk-type x) #x04)))
(define (heartbeat-ack-chunk? x)
  (and (chunk? x) (= (get-chunk-type x) #x05)))
(define (abort-chunk? x)
  (and (chunk? x) (= (get-chunk-type x) #x06)))
(define (shutdown-chunk? x)
  (and (chunk? x) (= (get-chunk-type x) #x07)))
(define (shutdown-ack-chunk? x)
  (and (chunk? x) (= (get-chunk-type x) #x08)))
(define (error-chunk? x)
  (and (chunk? x) (= (get-chunk-type x) #x09)))
(define (cookie-echo-chunk? x)
  (and (chunk? x) (= (get-chunk-type x) #x0a)))
(define (cookie-ack-chunk? x)
  (and (chunk? x) (= (get-chunk-type x) #x0b)))
(define (ecne-chunk? x)
  (and (chunk? x) (= (get-chunk-type x) #x0c)))
(define (cwr-chunk? x)
  (and (chunk? x) (= (get-chunk-type x) #x0d)))
(define (shutdown-complete-chunk? x)
  (and (chunk? x) (= (get-chunk-type x) #x0e)))
(define (forward-tsn-chunk? x)
  (and (chunk? x) (= (get-chunk-type x) #xc0)))

(define (heartbeat-parameter? x)
  (and (parameter? x) (= (get-parameter-type x) #x0001)))
(define (ipv4-address-parameter? x)
  (and (parameter? x) (= (get-parameter-type x) #x0005)))
(define (ipv6-address-parameter? x)
  (and (parameter? x) (= (get-parameter-type x) #x0006)))
(define (cookie-parameter? x)
  (and (parameter? x) (= (get-parameter-type x) #x0007)))
(define (unrecognized-parameter-parameter? x)
  (and (parameter? x) (= (get-parameter-type x) #x0008)))
(define (cookie-preservative-parameter? x)
  (and (parameter? x) (= (get-parameter-type x) #x0009)))
(define (hostname-parameter? x)
  (and (parameter? x) (= (get-parameter-type x) #x000b)))
(define (supported-address-type-parameter? x)
  (and (parameter? x) (= (get-parameter-type x) #x000c)))
(define (ecn-capable-parameter? x)
  (and (parameter? x) (= (get-parameter-type x) #x8000)))
(define (forward-tsn-supported-parameter? x)
  (and (parameter? x) (= (get-parameter-type x) #xc000)))

(define sctp-send sctp-send-with-crc32c)
(define sctp-send-raw sctp-send-raw-with-crc32c)